dataset_parameters:
  images_folder: 'data/cedarbay/images'         # Path to test images
  depth_maps_folder: 'data/cedarbay/depth_maps' # Path to test depth maps
  image_height: 768
  image_width: 1024
  image_channels: 3
  depth_channels: 1
  batch_size: 8
  training_ratio: 0.80
  validation_ratio: 0.15
  test_ratio: 0.05
  shuffle: True
  crop_pixels: 120
  pose_csv_path: 'data\cedarbay\Filtered_Relative_FFC_Pose_Euler.csv'  # Path to pose CSV
  pose_channels:
    vanilla: 0
    rel_z: 1
    rel_z_pitch_roll: 3
  percentiles_path: 'utils/percentiles.npz'
  pose_normalization_params_path: "data/cedarbay/pose_stats.json"

model_parameters:
  input_shapes:
    vanilla: [768, 1024, 3]
    rel_z: [768, 1024, 4]
    rel_z_pitch_roll: [768, 1024, 6]
  num_classes: 1  # Depth estimation is a regression task

inference_parameters:
  model_variant: 'rel_z_pitch_roll'  # Options: 'vanilla', 'rel_z', 'rel_z_pitch_roll' 
  models:
    vanilla:
      saved_model_path: 'saved_models/cedarbay_vanilla_model_unet_v3'  # Exact path to trained model weights
      output_dir: 'inference_results/vanilla_v3'  # Directory to save predictions and visualizations
    rel_z:
      checkpoint_file: 'checkpoints\cedarbay_rel_z\cedarbay_rel_z_model_unet-23.ckpt' 
      saved_model_path: 'saved_models/cedarbay_rel_z_model_unet'  
      output_dir: 'inference_results/rel_z'  
    rel_z_pitch_roll:
      checkpoint_file: 'checkpoints\cedarbay_rel_z\cedarbay_rel_z_pitch_roll_model_unet-47.ckpt'
      saved_model_path: 'saved_models/cedarbay_rel_z_pitch_roll_model_unet'
      save_best_model_path: 'saved_models\cedarbay_rel_z_pitch_roll_model_unet_epoch_47'
      output_dir: 'inference_results/rel_z_pitch_roll_epoch_47'  
  visualize: true                # Whether to generate visualizations
  save_predictions: true         # Whether to save prediction maps
  save_error_maps: true          # Whether to save error maps

logging_parameters:
  log_dir: 'logs/inference'       # Directory for inference logs 
