dataset_parameters:
  images_folder: 'data/cedarbay/images'
  depth_maps_folder: 'data/cedarbay/depth_maps'
  image_height: 768
  image_width: 1024
  image_channels: 3
  depth_channels: 1
  batch_size: 8
  train_test_split: 0.75
  shuffle: True
  crop_pixels: 120  # Based on empirical analysis
  pose_csv_path: 'data/cedarbay/computed_FFC_relative_pose_data.csv'  # Path to pose CSV
  pose_channels_vanilla: 0  # No pose channels for vanilla model
  pose_channels_rel_z: 1  # Relative Z for Model 2
  pose_channels_rel_z_pitch_roll: 3  # Relative Z, Pitch, Roll for Model 3
  percentiles_path: 'utils/percentiles.npz'

experiment_parameters:
  learning_rate: 0.00001
  epochs: 50
  saved_model_dir: 'saved_models/cedarbay_model_unet_finetuned'
  checkpoint_dir: 'checkpoints/cedarbay'
  checkpoint_file: 'checkpoints/cedarbay/cedarbay_model_unet_finetuned-{epoch:02d}.ckpt'
  pretrain: True  # Set to True to load pre-trained weights

model_parameters:
  input_shapes:
    vanilla: [768, 1024, 3]  # image_height x image_width x channels
    rel_z: [768, 1024, 4]
    rel_z_pitch_roll: [768, 1024, 6]
  num_classes: 1  # Depth estimation is a regression task

logging_parameters:
  tensorboard_log_dir: 'logs/tensorboard'